name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.event.repository.name }}
        
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chunwarayut/${{ steps.string.outputs.lowercase }}:latest
        
        
    - name: SSH Command
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        private_key: ${{ secrets.SSH_KEY }}
        command: docker pull chunwarayut/${{ steps.string.outputs.lowercase }}:latest && docker stop ${{ steps.string.outputs.lowercase }} && docker rm ${{ steps.string.outputs.lowercase }} && docker run --name ${{ steps.string.outputs.lowercase }} --restart=always -d -p 7010:3333 -e PORT=3333 -e MONGO_URI=mongodb://shorteneruser:HPz2X98Uzpzj22TeUtBxpxnU@128.199.79.240:27017/shortenerdb -e BASE=http://167.71.220.88:3333 chunwarayut/${{ steps.string.outputs.lowercase }} 
